apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::151187558444:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-M1O2YYU22YCQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::151187558444:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-25T21:50:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1832"
  uid: 08b67fe5-8f9f-4ca9-a4d2-7e1b52ddcd72
